(()=>{
  const F="CHURCH";
  Object.assign(EQUIPMENT,{
    church_training_sword:{id:"church_training_sword",name:"教團訓練劍",kind:"WEAPON",weaponKind:"SWORD",attackType:"SLASH",element:"NONE",affixes:[],defenseProfiles:[{id:"church_sword_parry",method:"PARRY",name:"長劍招架",vs:{SLASH:{chance:65},PIERCE:{chance:60},SHOT:{chance:10},STRIKE:{chance:0},MAGIC:{chance:0}}}]},
    church_greatsword:{id:"church_greatsword",name:"聖殿雙手劍",kind:"WEAPON",weaponKind:"GREATSWORD",attackType:"SLASH",element:"HOLY",affixes:[],defenseProfiles:[{id:"church_greatsword_parry",method:"PARRY",name:"雙手劍招架",vs:{SLASH:{chance:75},PIERCE:{chance:70},SHOT:{chance:15},STRIKE:{chance:10},MAGIC:{chance:0}}}]},
    church_saint_greatsword:{id:"church_saint_greatsword",name:"常駐神聖附魔雙手劍",kind:"WEAPON",weaponKind:"GREATSWORD",attackType:"SLASH",element:"HOLY",affixes:[],defenseProfiles:[{id:"saint_greatsword_parry",method:"PARRY",name:"聖劍招架",vs:{SLASH:{chance:85},PIERCE:{chance:80},SHOT:{chance:25},STRIKE:{chance:15},MAGIC:{chance:0}}}]},
    church_heavy_plate:{id:"church_heavy_plate",name:"教團重甲",kind:"ARMOR",type:"HEAVY",types:["HEAVY"],element:"NONE",affixes:[]},
    church_templar_plate:{id:"church_templar_plate",name:"聖殿騎士重甲",kind:"ARMOR",type:"HEAVY",types:["HEAVY"],element:"HOLY",affixes:[]},
    church_bishop_robe:{id:"church_bishop_robe",name:"主教法衣",kind:"ARMOR",type:"LIGHT",types:["LIGHT"],element:"HOLY",affixes:[]}
  });
  Object.assign(PASSIVES,{CHURCH_GUARDIAN:{id:"CHURCH_GUARDIAN",name:"聖殿援護",category:"PASSIVE",defenseProfiles:[{id:"church_guard_ally",method:"GUARD",name:"聖殿援護",canGuardAlly:true,vs:{SLASH:{damageMultiplier:.55},PIERCE:{damageMultiplier:.60},SHOT:{damageMultiplier:.55},STRIKE:{damageMultiplier:.70},MAGIC:{damageMultiplier:.80}}}]}});
  Object.assign(SKILLS,{
    church_slash:{id:"church_slash",name:"騎士斬擊",category:"ATTACK",weapon:"sword",power:1,range:{min:1,max:1},attackType:"INHERIT",element:"INHERIT",speed:0,target:"ENEMY",support:false,resource:{type:"UNLIMITED"}},
    church_heavy_slash:{id:"church_heavy_slash",name:"重劍斬擊",category:"ATTACK",weapon:"greatsword",power:1.1,range:{min:1,max:1},attackType:"SLASH",element:"INHERIT",speed:-5,target:"ENEMY",support:false,resource:{type:"UNLIMITED"}},
    church_holy_bolt:{id:"church_holy_bolt",name:"聖光術",category:"MAGIC",weapon:"staff",power:1,range:{min:1,max:4},attackType:"MAGIC",element:"HOLY",speed:0,target:"ENEMY",support:true,resource:{type:"UNLIMITED"}},
    templar_holy_slash:{id:"templar_holy_slash",name:"聖光斬",category:"ATTACK",weapon:"greatsword",power:1.2,range:{min:1,max:1},attackType:"SLASH",element:"HOLY",defenseStat:"MDEF",speed:0,target:"ENEMY",support:false,resource:{type:"UNLIMITED"}},
    templar_charge:{id:"templar_charge",name:"衝鋒",category:"ATTACK",weapon:"greatsword",power:1.15,range:{min:2,max:4},attackType:"SLASH",element:"INHERIT",speed:5,target:"ENEMY",support:false,resource:{type:"USES",max:3},approach:{type:"CHARGE",stopDistance:1}},
    templar_holy_shield:{id:"templar_holy_shield",name:"聖盾",category:"MAGIC",power:0,range:{min:0,max:0},target:"SELF",support:false,resource:{type:"USES",max:2},effects:[{type:"BUFF",id:"HOLY_SHIELD",classification:"POSITIVE",duration:2,modifiers:{damageTakenMultiplier:.65,guardMultiplier:.75},collision:{kind:"SHIELD",solid:true,height:3,hardness:4,response:"STOP",impactMultiplier:1.35,priority:100}}]},
    templar_healing:{id:"templar_healing",name:"治療術",category:"MAGIC",power:0,range:{min:1,max:3},target:"ALLY_OR_ENEMY",support:false,resource:{type:"USES",max:3},relationEffects:[{relation:"ALLY",type:"HEAL",amount:65},{relation:"SELF",type:"HEAL",amount:65},{relation:"ENEMY",type:"MAGIC_DAMAGE",power:.8,element:"HOLY",traitMultipliers:{UNDEAD:2}}]},
    saint_heal:{id:"saint_heal",name:"治癒祈禱",category:"MAGIC",power:0,range:{min:1,max:4},target:"ALLY",support:false,resource:{type:"USES",max:4},effects:[{type:"HEAL",amount:95}]},
    saint_dispel:{id:"saint_dispel",name:"淨化祈禱",category:"MAGIC",power:0,range:{min:1,max:4},target:"ALLY",support:false,resource:{type:"USES",max:3},effects:[{type:"DISPEL",classification:"NEGATIVE"}]},
    saint_blessing:{id:"saint_blessing",name:"祝福",category:"MAGIC",power:0,range:{min:1,max:4},target:"ALLY",support:false,resource:{type:"USES",max:3},effects:[{type:"BUFF",id:"SAINT_BLESSING",classification:"POSITIVE",duration:2,modifiers:{atk:10,matk:10,def:10,mdef:10}}]}
  });
  const raw={
    church_apprentice:{id:"church_apprentice",name:"騎士學徒",faction:F,archetype:"MELEE",attributes:{str:11,agi:10,int:7,wil:10,vit:11,luk:8},combat:{hp:230,atk:74,matk:35,def:62,mdef:52,move:4},armorId:"imperial_medium_armor",weaponIds:{sword:"church_training_sword"},skills:["church_slash"]},
    church_heavy_knight:{id:"church_heavy_knight",name:"重裝騎士",faction:F,archetype:"DEFENDER",attributes:{str:14,agi:7,int:7,wil:12,vit:15,luk:8},combat:{hp:300,atk:82,matk:38,def:96,mdef:62,move:3},armorId:"church_heavy_plate",weaponIds:{greatsword:"church_greatsword"},passives:["CHURCH_GUARDIAN"],skills:["church_heavy_slash"]},
    church_templar:{id:"church_templar",name:"聖殿騎士",faction:F,archetype:"DEFENDER",attributes:{str:16,agi:10,int:10,wil:16,vit:17,luk:9},combat:{hp:285,atk:90,matk:60,def:90,mdef:78,move:4},armorId:"church_templar_plate",weaponIds:{greatsword:"church_greatsword"},passives:["CHURCH_GUARDIAN"],skills:["church_heavy_slash","church_holy_bolt"]},
    church_bishop:{id:"church_bishop",name:"主教",faction:F,archetype:"HEALER",attributes:{str:7,agi:9,int:17,wil:18,vit:11,luk:12},combat:{hp:205,atk:40,matk:94,def:45,mdef:92,move:4},armorId:"church_bishop_robe",weaponIds:{staff:"imperial_staff"},skills:["church_holy_bolt","saint_heal","saint_dispel"]},
    church_templar_hero:{id:"church_templar_hero",name:"女聖殿騎士",faction:F,race:"ANCIENT_HUMAN",archetype:"TEMPLAR_HERO",genetics:{grade:"3V"},attributes:{str:20,agi:16,int:14,wil:20,vit:20,luk:13},combat:{hp:320,atk:108,matk:82,def:104,mdef:92,move:4},armorId:"church_templar_plate",weaponIds:{greatsword:"church_saint_greatsword"},passives:["CHURCH_GUARDIAN"],skills:["templar_holy_slash","templar_charge","templar_holy_shield","templar_healing"],lore:{genetics:"3V",notes:"亡國王女、聖女之姊。逃亡時妹妹覺醒，雙手劍自此維持常駐神聖附魔。"}},
    church_saint:{id:"church_saint",name:"聖女",faction:F,race:"ANCIENT_HUMAN",archetype:"SAINT",genetics:{grade:"3V"},attributes:{str:9,agi:14,int:20,wil:20,vit:13,luk:20},combat:{hp:215,atk:42,matk:110,def:48,mdef:108,move:4},armorId:"church_bishop_robe",weaponIds:{staff:"imperial_staff"},skills:["saint_heal","saint_dispel","saint_blessing"],lore:{genetics:"3V",notes:"亡國王女、女聖殿騎士之妹。以治療、驅散與祝福為核心。"}}
  };
  Object.entries(raw).forEach(([id,c])=>CHARACTERS[id]=EquipmentDatabase.resolveCharacter(c));
  Object.assign(CARDS,{
    church_apprentice_card:{id:"church_apprentice_card",name:"騎士學徒",type:"CHARACTER",characterId:"church_apprentice",faction:F,unitType:"UNIT",cost:3},
    church_heavy_knight_card:{id:"church_heavy_knight_card",name:"重裝騎士",type:"CHARACTER",characterId:"church_heavy_knight",faction:F,unitType:"UNIT",cost:4},
    church_templar_card:{id:"church_templar_card",name:"聖殿騎士",type:"CHARACTER",characterId:"church_templar",faction:F,unitType:"UNIT",cost:5},
    church_bishop_card:{id:"church_bishop_card",name:"主教",type:"CHARACTER",characterId:"church_bishop",faction:F,unitType:"UNIT",cost:4},
    church_templar_hero_card:{id:"church_templar_hero_card",name:"女聖殿騎士",type:"CHARACTER",characterId:"church_templar_hero",faction:F,unitType:"HERO",cost:6},
    church_redemption_card:{id:"church_redemption_card",name:"救贖",type:"SPELL",spellType:"REVIVE",faction:F,cost:6,effect:{type:"REVIVE",zone:"GRAVEYARD"}},
    church_dispel_card:{id:"church_dispel_card",name:"驅散",type:"SPELL",spellType:"DISPEL",faction:F,cost:3,effect:{type:"DISPEL",classification:"NEGATIVE",target:"ALLY"}},
    church_judgement_card:{id:"church_judgement_card",name:"懲戒",type:"SPELL",spellType:"TACTICAL",faction:F,cost:5,effect:{type:"AREA_RELATION",radius:1,effects:[{relation:"ALLY",type:"HEAL",amount:60},{relation:"ENEMY",type:"MAGIC_DAMAGE",amount:65,element:"HOLY",traitMultipliers:{UNDEAD:2}}]}},
    church_entrenchment_card:{id:"church_entrenchment_card",name:"陣地戰",type:"SPELL",spellType:"BUFF",faction:F,cost:4,effect:{type:"AREA_BUFF",radius:2,duration:3,targetFilter:{relation:"ALLY",faction:F},buff:{id:"CHURCH_ENTRENCHMENT",classification:"POSITIVE",modifiers:{def:15,mdef:10,guardMultiplier:.8}}}},
    church_saint_card:{id:"church_saint_card",name:"聖女",type:"CHARACTER",characterId:"church_saint",faction:F,unitType:"HERO",cost:6,pack:"SAINT_SUPPLEMENT"}
  });
})();