import * as Hydrology from "./hydrology-engine.js";
import * as Climate from "./climate-engine.js";
import * as Resolver from "./environment-resolver.js";
import { TERRAINS } from "./terrain-database.js";
import { equippedItems } from "./equipment-runtime.js";
export const ELEMENT=Object.freeze({NONE:"NONE",GRASS:"GRASS",WATER:"WATER",STONE:"STONE"});
export const FORCE=Object.freeze({FIRE:"FIRE",HEAVY_FIRE:"HEAVY_FIRE",EXPLOSION:"EXPLOSION",WIND:"WIND",THUNDER:"THUNDER",IMPACT:"IMPACT",AVALANCHE_TRIGGER:"AVALANCHE_TRIGGER"});
export const EFFECT=Object.freeze({BURNING:"BURNING",BOILING:"BOILING",STEAM:"STEAM",FRAGMENTS:"FRAGMENTS",TORNADO:"TORNADO",FIRE_TORNADO:"FIRE_TORNADO",ELECTRIFIED:"ELECTRIFIED",SNOW:"SNOW",ICE:"ICE",CURRENT:"CURRENT"});
export const WEATHER=Object.freeze({CLEAR:"CLEAR",FOG:"FOG",RAIN:"RAIN",HEAVY_RAIN:"HEAVY_RAIN",THUNDERSTORM:"THUNDERSTORM",SNOW:"SNOW",BLIZZARD:"BLIZZARD"});
export const WEATHER_TURNS=Object.freeze({FOG:2,RAIN:3,HEAVY_RAIN:2,THUNDERSTORM:2,SNOW:3,BLIZZARD:2});
export const HAZARD=Object.freeze({BURNING_DAMAGE:20,BOILING_DAMAGE:30,FIRE_TORNADO_DAMAGE:45,ELECTRIC_DAMAGE:35});
const WEATHER_RULES={THUNDERSTORM:{lightningChance:.35,lightningDamage:60,metalWeight:2,waterWeight:2,treeWeight:2}},DIRS=[[1,0],[-1,0],[0,1],[0,-1]],key=(x,y)=>`${x},${y}`;
const METAL=new Set(["black_sword","imperial_sword","standard_sword","blessed_sword","imperial_spear","imperial_hammer","imperial_medium_armor","imperial_heavy_shield_armor","water_medium_armor","imperial_heavy_armor","imperial_heavy_plate","imperial_large_shield"]);
const tileAt=(m,x,y)=>m?.tiles?.find(t=>t.x===x&&t.y===y)||null, objectAt=(m,x,y)=>(m?.objects||[]).find(o=>!o.destroyed&&o.x===x&&o.y===y)||null;
export function environmentAt(map,x,y){const o=objectAt(map,x,y);if(o?.environment)return o.environment;const t=tileAt(map,x,y);return TERRAINS[t?.terrain]?.environment||ELEMENT.NONE}
export function createEnvironmentState({timeOfDay="DAY",weather="CLEAR",weatherTurns=null}={}){return{timeOfDay,weather:weather||WEATHER.CLEAR,weatherTurnsRemaining:weatherTurns==null?null:Math.max(0,Number(weatherTurns||0)),effects:new Map(),destroyedObjects:new Set(),climate:{turn:0}}}
export const isRain=s=>s?.weather===WEATHER.RAIN||s?.weather===WEATHER.HEAVY_RAIN||s?.weather===WEATHER.THUNDERSTORM;
export const isSnow=s=>s?.weather===WEATHER.SNOW||s?.weather===WEATHER.BLIZZARD;
function rainAmount(w){return w===WEATHER.THUNDERSTORM?Hydrology.STORM_RAIN_FILL_PER_EVENT:w===WEATHER.HEAVY_RAIN?Hydrology.HEAVY_RAIN_FILL_PER_EVENT:Hydrology.RAIN_FILL_PER_EVENT}
function weatherPulse(map,state,events=[]){if(isRain(state))events.push(...Hydrology.applyRain(map,{heavy:state.weather!==WEATHER.RAIN,amount:rainAmount(state.weather),source:state.weather}));else if(!isSnow(state))events.push(...Hydrology.drySoil(map,{source:"CLEAR_WEATHER"}));events.push(...Climate.advanceClimate(map,state));events.push(...Resolver.resolveEnvironment(map,state,{source:"ENVIRONMENT_TICK"}));return events}
function flammableAt(map,x,y){const t=tileAt(map,x,y);if(!t||Hydrology.isWater(t))return false;const o=objectAt(map,x,y);if(o&&(o.flammable===true||o.environment===ELEMENT.GRASS))return true;return TERRAINS[t.terrain]?.environment===ELEMENT.GRASS}
export function effectAt(state,x,y){return state?.effects?.get(key(x,y))||[]}
export function addEffect(state,x,y,effect){const k=key(x,y),list=state.effects.get(k)||[],same=list.find(e=>e.type===effect.type);if(same)Object.assign(same,effect);else list.push({...effect,x,y});state.effects.set(k,list);return same||list[list.length-1]}
export function removeEffect(state,x,y,type){const k=key(x,y),next=(state.effects.get(k)||[]).filter(e=>e.type!==type);if(next.length)state.effects.set(k,next);else state.effects.delete(k)}
export const isBurning=(s,x,y)=>effectAt(s,x,y).some(e=>e.type===EFFECT.BURNING||e.type===EFFECT.FIRE_TORNADO);
export function spreadFire(map,state){if(!map||!state||isRain(state)||isSnow(state))return[];const pending=new Map();for(const[k,list]of state.effects.entries()){if(!list.some(e=>e.type===EFFECT.BURNING||e.type===EFFECT.FIRE_TORNADO))continue;const[x,y]=k.split(",").map(Number);for(const[dx,dy]of DIRS){const nx=x+dx,ny=y+dy,nk=key(nx,ny);if(pending.has(nk)||isBurning(state,nx,ny)||!flammableAt(map,nx,ny))continue;pending.set(nk,{x:nx,y:ny})}}const events=[];for(const{x,y}of pending.values()){addEffect(state,x,y,{type:EFFECT.BURNING,duration:3,lightRadius:2,damage:HAZARD.BURNING_DAMAGE,damageType:"FIRE",fireIntensity:"NORMAL"});events.push({type:"IGNITE",x,y,effect:EFFECT.BURNING,source:"FIRE_SPREAD"})}return events}
export function advanceEnvironment(map,state){if(!map||!state)return[];const events=[];if(state.weather!==WEATHER.CLEAR&&state.weatherTurnsRemaining===0){const ended=state.weather;state.weather=WEATHER.CLEAR;state.weatherTurnsRemaining=null;events.push({type:"WEATHER_ENDED",weather:ended})}weatherPulse(map,state,events);if(state.weather!==WEATHER.CLEAR&&state.weatherTurnsRemaining!=null)state.weatherTurnsRemaining=Math.max(0,Number(state.weatherTurnsRemaining||0)-1);events.push(...spreadFire(map,state));return events}
export function setWeather(state,weather,map=null,{duration=null,applyPulse=true}={}){if(!state)return[];const resolved=WEATHER[weather]?weather:WEATHER.CLEAR;state.weather=resolved;state.weatherTurnsRemaining=resolved===WEATHER.CLEAR?null:Math.max(1,Number(duration??WEATHER_TURNS[resolved]??1));const events=[];if(isRain(state)||isSnow(state)){for(const[k,list]of[...state.effects.entries()]){if(!list.some(e=>e.type===EFFECT.BURNING))continue;const[x,y]=k.split(",").map(Number);removeEffect(state,x,y,EFFECT.BURNING);events.push({type:isRain(state)?"RAIN_EXTINGUISHED_FIRE":"SNOW_EXTINGUISHED_FIRE",x,y})}}if(map&&applyPulse){weatherPulse(map,state,events);state.weatherTurnsRemaining=Math.max(0,Number(state.weatherTurnsRemaining||0)-1)}events.push({type:"WEATHER_SET",weather:resolved,duration:resolved===WEATHER.CLEAR?0:Number(duration??WEATHER_TURNS[resolved]??1),remaining:Number(state.weatherTurnsRemaining??0)});return events}
function hasMetalEquipment(unit){return equippedItems(unit?.character).some(item=>item?.material==="METAL"||item?.conductive===true||METAL.has(item?.id))}
export function lightningRisk(map,unit){if(!unit?.alive)return{weight:0,reasons:[]};const rules=WEATHER_RULES.THUNDERSTORM;let weight=1;const reasons=[];if(hasMetalEquipment(unit)){weight*=rules.metalWeight;reasons.push("METAL")}const material=environmentAt(map,unit.gridX??unit.x,unit.gridY??unit.y);if(material===ELEMENT.WATER){weight*=rules.waterWeight;reasons.push("WATER")}if(material===ELEMENT.GRASS){weight*=rules.treeWeight;reasons.push("TREE")}return{weight,reasons}}
export function rollWeatherEvent({map,state,units=[],random=Math.random}){if(!state||state.weather!==WEATHER.THUNDERSTORM)return[];const rules=WEATHER_RULES.THUNDERSTORM;if(random()>=rules.lightningChance)return[];const candidates=units.filter(u=>u?.alive).map(unit=>({unit,...lightningRisk(map,unit)})).filter(x=>x.weight>0);if(!candidates.length)return[];let roll=random()*candidates.reduce((n,x)=>n+x.weight,0),chosen=candidates[candidates.length-1];for(const candidate of candidates){roll-=candidate.weight;if(roll<=0){chosen=candidate;break}}return[{type:"LIGHTNING_STRIKE",unit:chosen.unit,x:chosen.unit.gridX??chosen.unit.x,y:chosen.unit.gridY??chosen.unit.y,damage:rules.lightningDamage,riskReasons:chosen.reasons,weight:chosen.weight}]}
export function visionModifier(state,x,y){const effects=effectAt(state,x,y);if(effects.some(e=>e.type===EFFECT.STEAM))return{blocked:true,reason:"STEAM"};if(state?.weather===WEATHER.BLIZZARD)return{blocked:false,dark:true,reason:"BLIZZARD"};if(state?.weather===WEATHER.FOG)return{blocked:false,dark:true,reason:"FOG"};return{blocked:false,dark:false,reason:null}}
export function visionRange(state){if(state?.weather===WEATHER.BLIZZARD)return 3;if(state?.weather===WEATHER.FOG)return 4;return Infinity}
